{
 "title": "HybridCache_LoadTest",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "App total memory usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_private_memory_bytes{instance=\"host.docker.internal:5000\"}/1024 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"host.docker.internal:5000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request in Queue",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "HybirdRedisCache_requests_queued{job=\"weather_api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(HybirdRedisCache_response_latency_ms_bucket{job=\"weather_api\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(HybirdRedisCache_requests_processed_total{job=\"weather_api\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Failed GETs ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_received_total{code!=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "HybirdRedisCache_requests_processed_total{job=\"weather_api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"weather_api\", instance=\"host.docker.internal:5000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests in progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "HybirdRedisCache_requests_queued{job=\"weather_api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Requests in progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "http_requests_in_progress{action=\"Get\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}